# Notebook 1

In [1]:
# Mandatory operation for importing custom libraries
from pathlib import Path
import sys

cwd = Path.cwd()
base = cwd.parent
sys.path.append(str(base))

In [2]:
# Testing FileManager
from file_manager.file_manager import FileManager

file_manager = FileManager()
print(file_manager.data_folder)

c:\Users\User\Desktop\Hi!ckathon\hickathon5\data


# Load data

In [3]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [4]:
train_data = file_manager.load_training_data()
test_data = file_manager.load_test_data()
tiny_train_data = file_manager.load_tiny_training_data()

c:\Users\User\Desktop\Hi!ckathon\hickathon5\code\file_manager\file_manager.py:40: DtypeWarning: Columns (108,110,111,115,117,118,122,124,125) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(self.training_data_file, index_col='row_index')
c:\Users\User\Desktop\Hi!ckathon\hickathon5\code\file_manager\file_manager.py:45: DtypeWarning: Columns (1,5,108,110,111,115,117,118,122,124,125) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(self.test_data_file, index_col='row_index')


# Rough look at data

In [5]:
test_data.head()

piezo_station_department_code      piezo_station_update_date  \
row_index                                                                
2331795                              01  Sun Jul 14 13:00:02 CEST 2024   
2331796                              01  Sun Jul 14 13:00:02 CEST 2024   
2331797                              01  Sun Jul 14 13:00:02 CEST 2024   
2331798                              01  Sun Jul 14 13:00:02 CEST 2024   
2331799                              01  Sun Jul 14 13:00:02 CEST 2024   

           piezo_station_investigation_depth piezo_station_department_name  \
row_index                                                                    
2331795                                20.00                           Ain   
2331796                                35.60                           Ain   
2331797                                35.22                           Ain   
2331798                                34.20                           Ain   
2331799                                37.30                           Ain   

          piezo_station_commune_code_insee  \
row_index                                    
2331795                              01073   
2331796                              01363   
2331797                              01244   
2331798                              01288   
2331799                              01422   

                                      piezo_station_pe_label  \
row_index                                                      
2331795    PIEZOMETRE - MARAIS DE LAVOURS (CEYZERIEU - BR...   
2331796    PIEZOMETRE - GRAVIERE (ST-JEAN-LE-VIEUX - BRGM...   
2331797    PIEZOMETRE - BORD AUTOROUTE (MEXIMIEUX - BRGM ...   
2331798           PIEZOMETRE - GRENY (PERON - BRGM 01) - BSH   
2331799            FORAGE - ENCLOS (TOSSIAT - BRGM 01) - BSH   

          piezo_station_bdlisa_codes  piezo_station_altitude  \
row_index                                                      
2331795                  ['712AH37']                  232.00   
2331796                  ['712GB05']                  247.25   
2331797                  ['040AJ43']                  218.77   
2331798       ['516AA00', '516AF00']                  499.85   
2331799                  ['507AB00']                  260.00   

          piezo_station_bss_code piezo_station_commune_name  \
row_index                                                     
2331795         07004X0046/D6-20                  Ceyzérieu   
2331796            06754X0077/F1        Saint-Jean-le-Vieux   
2331797        06993X0226/MEXI_2                  Meximieux   
2331798            06533X0070/F2                      Péron   
2331799            06518X0026/P2                    Tossiat   

           piezo_station_longitude  piezo_station_latitude  \
row_index                                                    
2331795                   5.748241               45.828148   
2331796                   5.356637               46.028102   
2331797                   5.220795               45.895734   
2331798                   5.948977               46.201180   
2331799                   5.313353               46.136402   

          piezo_station_bss_id     piezo_bss_code piezo_measurement_date  \
row_index                                                                  
2331795             BSS001TTQQ   07004X0046/D6-20             2022-06-01   
2331796             BSS001SCTM      06754X0077/F1             2022-06-01   
2331797             BSS001TRPH  06993X0226/MEXI_2             2022-06-01   
2331798             BSS001RGXM      06533X0070/F2             2022-06-01   
2331799             BSS001RFRV      06518X0026/P2             2022-06-01   

          piezo_obtention_mode               piezo_status piezo_qualification  \
row_index                                                                       
2331795         Valeur mesurée  Donnée contrôlée niveau 2            Correcte   
2331796         Valeur mesurée  Donnée contrôlée niveau 2            C

In [6]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 611208 entries, 2331795 to 3610822
Columns: 134 entries, piezo_station_department_code to insee_%_const
dtypes: float64(90), int64(5), object(39)
memory usage: 629.5+ MB


In [7]:
test_data.isna().sum()

piezo_station_department_code                0
piezo_station_update_date                    0
piezo_station_investigation_depth        38853
piezo_station_department_name                0
piezo_station_commune_code_insee             0
piezo_station_pe_label                   48457
piezo_station_bdlisa_codes               29700
piezo_station_altitude                       0
piezo_station_bss_code                       0
piezo_station_commune_name                   0
piezo_station_longitude                      0
piezo_station_latitude                       0
piezo_station_bss_id                         0
piezo_bss_code                               0
piezo_measurement_date                       0
piezo_obtention_mode                         0
piezo_status                                 0
piezo_qualification                          0
piezo_continuity_code                        0
piezo_continuity_name                        0
piezo_producer_code                      19917
piezo_produce

In [8]:
test_data.columns

Index(['piezo_station_department_code', 'piezo_station_update_date',
       'piezo_station_investigation_depth', 'piezo_station_department_name',
       'piezo_station_commune_code_insee', 'piezo_station_pe_label',
       'piezo_station_bdlisa_codes', 'piezo_station_altitude',
       'piezo_station_bss_code', 'piezo_station_commune_name',
       ...
       'prelev_volume_obtention_mode_label_2', 'prelev_longitude_2',
       'prelev_latitude_2', 'prelev_commune_code_insee_2',
       'prelev_other_volume_sum', 'insee_%_agri', 'insee_pop_commune',
       'insee_med_living_level', 'insee_%_ind', 'insee_%_const'],
      dtype='object', length=134)

In [9]:
# Filter by column key
test_data[test_data.columns[test_data.columns.str.startswith('piezo')]]

piezo_station_department_code      piezo_station_update_date  \
row_index                                                                
2331795                              01  Sun Jul 14 13:00:02 CEST 2024   
2331796                              01  Sun Jul 14 13:00:02 CEST 2024   
2331797                              01  Sun Jul 14 13:00:02 CEST 2024   
2331798                              01  Sun Jul 14 13:00:02 CEST 2024   
2331799                              01  Sun Jul 14 13:00:02 CEST 2024   
...                                 ...                            ...   
3610818                              95  Thu Sep 19 11:45:47 CEST 2024   
3610819                              95  Thu Sep 19 14:41:55 CEST 2024   
3610820                              95  Thu Sep 19 14:29:16 CEST 2024   
3610821                              95   Thu Dec 14 19:02:16 CET 2023   
3610822                              95   Tue Jan 28 19:01:33 CET 2020   

           piezo_station_investigation_depth piezo_station_department_name  \
row_index                                                                    
2331795                                20.00                           Ain   
2331796                                35.60                           Ain   
2331797                                35.22                           Ain   
2331798                                34.20                           Ain   
2331799                                37.30                           Ain   
...                                      ...                           ...   
3610818                                24.00                    Val-d'Oise   
3610819                                25.50                    Val-d'Oise   
3610820                                30.00                    Val-d'Oise   
3610821                               630.00                    Val-d'Oise   
3610822                               104.00                    Val-d'Oise   

          piezo_station_commune_code_insee  \
row_index                                    
2331795                              01073   
2331796                              01363   
2331797                              01244   
2331798                              01288   
2331799                              01422   
...                                    ...   
3610818                              95119   
3610819                              95142   
3610820                              95610   
3610821                              95313   
3610822                              95509   

                                      piezo_station_pe_label  \
row_index                                                      
2331795    PIEZOMETRE - MARAIS DE LAVOURS (CEYZERIEU - BR...   
2331796    PIEZOMETRE - GRAVIERE (ST-JEAN-LE-VIEUX - BRGM...   
2331797    PIEZOMETRE - BORD AUTOROUTE (MEXIMIEUX - BRGM ...   
2331798           PIEZOMETRE - GRENY (PERON - BRGM 01) - BSH   
2331799            FORAGE - ENCLOS (TOSSIAT - BRGM 01) - BSH   
...                                                      ...   
3610818                Puits du hameau de Buchet (Buhy - 95)   
3610819         PIÉZOMÈTRE DU HAMEAU DE BERCAGNY (CHARS -95)   
3610820    Piézomètre de la place Roland Vasseur (Théméri...   
3610821           PIÉZOMÈTRE DE L'ISLE-ADAM (ISLE-ADAM - 95)   
3610822    Piézomètre de Puiseux-en-France (Puiseux-en-Fr...   

          piezo_station_bdlisa_codes  piezo_station_altitude  \
row_index                                                      
2331795                  ['712AH37']                  232.00   
2331796                  ['712GB05']                  247.25   
2331797                  ['040AJ43']                  218.77   
2331798       ['516AA00', '516AF00']                  499.85   
2331799                  ['507AB00']                  260.00   
...                              ...                     ...   
3610818                  ['121AZ01']                   63.00   
3610819                 

In [10]:
test_data.describe()

piezo_station_investigation_depth  piezo_station_altitude  \
count                      572355.000000           611208.000000   
mean                           85.769989              146.468334   
std                           241.824056              190.889950   
min                             0.000000             -999.000000   
25%                            16.470000               40.000000   
50%                            38.350000              107.000000   
75%                            80.000000              185.000000   
max                          5233.400000             2150.000000   

       piezo_station_longitude  piezo_station_latitude  piezo_continuity_code  \
count            611208.000000           611208.000000          611208.000000   
mean                  2.191367               46.382918               1.999084   
std                   2.698975                2.173051               0.030255   
min                  -4.657129               41.399732               1.000000   
25%                  -0.112823               44.472234               2.000000   
50%                   1.901276               46.305138               2.000000   
75%                   4.123897               48.186733               2.000000   
max                   9.519890               50.971087               2.000000   

       piezo_producer_code      meteo_id  meteo_latitude  meteo_longitude  \
count         5.912910e+05  6.112080e+05   611208.000000    611208.000000   
mean          4.994526e+12  3.761418e+07        2.167895        46.388743   
std           1.080798e+13  2.079943e+07        2.657972         2.138046   
min           5.300000e+01  1.027003e+06       -4.771667        42.384667   
25%           2.650000e+02  2.105600e+07       -0.152000        44.463167   
50%           3.000000e+02  3.421700e+07        1.903167        46.316333   
75%           1.219000e+03  5.246900e+07        4.155333        48.166333   
max           4.930211e+13  9.558000e+07        8.145500        50.833833   

       meteo_altitude  meteo_rain_height     meteo_DRR  meteo_temperature_min  \
count   611208.000000      604156.000000  69755.000000          591802.000000   
mean       166.120084           1.836326     45.945681              14.705736   
std        204.786272           5.273492    103.032319               3.850183   
min          1.000000           0.000000      0.000000              -3.700000   
25%         49.000000           0.000000      0.000000              12.300000   
50%        113.000000           0.000000      0.000000              14.900000   
75%        207.000000           0.800000     40.000000              17.300000   
max       2471.000000         281.700000   1171.000000              30.400000   

       meteo_time_tn  meteo_temperature_max  meteo_time_tx  \
count  583619.000000          591789.000000  583769.000000   
mean      512.936788              27.438380    1396.380659   
std       463.947102               5.008578     166.187837   
min         0.000000               2.900000       0.000000   
25%       333.000000              24.000000    1316.000000   
50%       424.000000              27.400000    1424.000000   
75%       511.000000              30.800000    1517.000000   
max      2359.000000              44.400000    2359.000000   

       meteo_temperature_avg  meteo_temperature_avg_threshold  \
count          585680.000000                    591762.000000   
mean               20.740348                        21.071985   
std                 3.909420                         3.849005   
min                -2.300000                        -0.400000   
25%                18.300000                        18.600000   
50%                20.700000                        21.150000   
75%                23.300000                        23.650000   
max                33.800000                        35.000000   

       meteo_temperature_min_ground  meteo_temperature_min_50cm  \
count                 162136

In [11]:
test_data.columns.str.startswith('piezo')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [12]:
tiny_train_data['piezo_groundwater_level_category']

row_index
0              High
1         Very High
2              High
3         Very High
4          Very Low
            ...    
105166     Very Low
105167         High
105168      Average
105169      Average
105170    Very High
Name: piezo_groundwater_level_category, Length: 100000, dtype: object

# Split raw data by variable category (piezo, weather, ...)

We are only interested in training data.

In [13]:
from pandas import DataFrame

# Function to extract variable category
def extract_category(
        df: DataFrame,
        category: str,
) -> DataFrame:
    return df[df.columns[df.columns.str.startswith(category)]]

In [14]:
hydro_variables = extract_category(tiny_train_data, 'hydro')
hydro_variables.head()

hydro_station_code hydro_observation_date_elab  \
row_index                                                  
0                 V142501001                  2020-01-01   
1                 V271201001                  2020-01-01   
2                 V294201001                  2020-01-01   
3                 V100001002                  2020-01-01   
4                 U400000101                  2020-01-01   

           hydro_observation_result_elab  hydro_status_code  \
row_index                                                     
0                                 1833.0                 16   
1                                93389.0                 16   
2                               108237.0                 16   
3                               305464.0                 16   
4                                   85.0                 12   

           hydro_status_label  hydro_method_code hydro_method_label  \
row_index                                                             
0              Donnée validée                 12      Interpolation   
1              Donnée validée                 12      Interpolation   
2              Donnée validée                 12      Interpolation   
3              Donnée validée                 12      Interpolation   
4          Donnée pré-validée                 12      Interpolation   

           hydro_qualification_code hydro_qualification_label  \
row_index                                                       
0                                20                     Bonne   
1                                20                     Bonne   
2                                20                     Bonne   
3                                12                  Douteuse   
4                                20                     Bonne   

           hydro_longitude  hydro_latitude hydro_hydro_quantity_elab  
row_index                                                             
0                 5.685831       45.874843                       QmJ  
1                 5.336428       46.047082                       QmM  
2                 5.233492       45.906423                       QmJ  
3                 5.964334       46.137641                       QmM  
4                 5.330754       46.143007                       QmJ

In [15]:
hydro_variables.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 105170
Data columns (total 12 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   hydro_station_code             100000 non-null  object 
 1   hydro_observation_date_elab    100000 non-null  object 
 2   hydro_observation_result_elab  100000 non-null  float64
 3   hydro_status_code              100000 non-null  int64  
 4   hydro_status_label             100000 non-null  object 
 5   hydro_method_code              100000 non-null  int64  
 6   hydro_method_label             100000 non-null  object 
 7   hydro_qualification_code       100000 non-null  int64  
 8   hydro_qualification_label      100000 non-null  object 
 9   hydro_longitude                100000 non-null  float64
 10  hydro_latitude                 100000 non-null  float64
 11  hydro_hydro_quantity_elab      100000 non-null  object 
dtypes: float64(3), int64(3), object(6)


## > Comment hydro info

Hydro data look fine 

# Pipeline

In [16]:
tiny_train_data_numerical = tiny_train_data.select_dtypes(include=['int64', 'float64'])
tiny_train_data_numerical.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 105170
Data columns (total 95 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   piezo_station_investigation_depth  93886 non-null   float64
 1   piezo_station_altitude             100000 non-null  float64
 2   piezo_station_longitude            100000 non-null  float64
 3   piezo_station_latitude             100000 non-null  float64
 4   piezo_continuity_code              100000 non-null  float64
 5   piezo_producer_code                94280 non-null   float64
 6   meteo_id                           100000 non-null  int64  
 7   meteo_latitude                     100000 non-null  float64
 8   meteo_longitude                    100000 non-null  float64
 9   meteo_altitude                     100000 non-null  int64  
 10  meteo_rain_height                  99157 non-null   float64
 11  meteo_DRR                          11420 non

In [17]:
tiny_train_data_Xy = tiny_train_data_numerical.join(tiny_train_data['piezo_groundwater_level_category'])
tiny_train_data_Xy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 105170
Data columns (total 96 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   piezo_station_investigation_depth  93886 non-null   float64
 1   piezo_station_altitude             100000 non-null  float64
 2   piezo_station_longitude            100000 non-null  float64
 3   piezo_station_latitude             100000 non-null  float64
 4   piezo_continuity_code              100000 non-null  float64
 5   piezo_producer_code                94280 non-null   float64
 6   meteo_id                           100000 non-null  int64  
 7   meteo_latitude                     100000 non-null  float64
 8   meteo_longitude                    100000 non-null  float64
 9   meteo_altitude                     100000 non-null  int64  
 10  meteo_rain_height                  99157 non-null   float64
 11  meteo_DRR                          11420 non

In [18]:
tiny_train_data_Xy.head()

piezo_station_investigation_depth  piezo_station_altitude  \
row_index                                                              
0                                      20.00                  232.00   
1                                      35.60                  247.25   
2                                      35.22                  218.77   
3                                      34.20                  499.85   
4                                      37.30                  260.00   

           piezo_station_longitude  piezo_station_latitude  \
row_index                                                    
0                         5.748241               45.828148   
1                         5.356637               46.028102   
2                         5.220795               45.895734   
3                         5.948977               46.201180   
4                         5.313353               46.136402   

           piezo_continuity_code  piezo_producer_code  meteo_id  \
row_index                                                         
0                            2.0                196.0   1034004   
1                            2.0                196.0   1089001   
2                            2.0                196.0   1027003   
3                            2.0                196.0  39413001   
4                            2.0                196.0   1072001   

           meteo_latitude  meteo_longitude  meteo_altitude  meteo_rain_height  \
row_index                                                                       
0                5.688000        45.769333             330                0.2   
1                5.329333        45.976500             250                0.0   
2                5.106667        45.833000             196                NaN   
3                5.843000        46.302833            1133                0.0   
4                5.287667        46.204333             260                0.0   

           meteo_DRR  meteo_temperature_min  meteo_time_tn  \
row_index                                                    
0                NaN                   -1.6          516.0   
1                0.0                   -2.2          306.0   
2                NaN                   -1.4          321.0   
3                NaN                   -2.3            NaN   
4                NaN                   -2.1          510.0   

           meteo_temperature_max  meteo_time_tx  meteo_temperature_avg  \
row_index                                                                
0                            3.9         1352.0                    0.7   
1                            0.0         1322.0                   -1.2   
2                            0.6         1524.0                   -0.6   
3                            7.7            NaN                    0.4   
4                            0.4         2034.0                   -0.8   

           meteo_temperature_avg_threshold  meteo_temperature_min_ground  \
row_index                                                                  
0                                     1.15                          -3.7   
1                                    -1.10                          -1.3   
2                                    -0.40                           NaN   
3                                     2.70                           NaN   
4                                    -0.85                           NaN   

           meteo_temperature_min_50cm  meteo_frost_duration  \
row_index                                                     
0                                 NaN                 577.0   
1                                -1.5                1440.0   
2                                 NaN                1228.0   
3                                 NaN                   NaN   
4                                 NaN                1103.0   

           meteo_amplitude_tn_tx  meteo_temperature_avg_tntm  \
row_index                               

In [19]:
tiny_train_data_Xy['meteo_DRR'].dropna()

row_index
1          0.0
6          0.0
11         0.0
14         0.0
17         0.0
          ... 
105152     0.0
105153    34.0
105158    83.0
105165    83.0
105170    83.0
Name: meteo_DRR, Length: 11420, dtype: float64

In [20]:
tiny_train_data_Xy['meteo_DRR']

row_index
0          NaN
1          0.0
2          NaN
3          NaN
4          NaN
          ... 
105166     NaN
105167     NaN
105168     NaN
105169     NaN
105170    83.0
Name: meteo_DRR, Length: 100000, dtype: float64

In [21]:
tiny_train_data_Xy['meteo_DRR'].unique()

array([      nan, 0.000e+00, 1.380e+02, 2.200e+01, 2.100e+01, 2.300e+02,
       2.650e+02, 1.000e+01, 3.800e+01, 9.100e+01, 2.800e+01, 2.540e+02,
       1.000e+02, 1.710e+02, 4.100e+01, 5.100e+01, 2.400e+01, 1.360e+02,
       3.500e+01, 1.540e+02, 4.500e+02, 6.100e+01, 3.260e+02, 5.460e+02,
       8.700e+01, 2.330e+02, 2.560e+02, 1.240e+02, 4.000e+01, 2.580e+02,
       6.200e+01, 1.070e+02, 2.700e+01, 5.400e+01, 3.600e+02, 7.000e+01,
       7.000e+00, 1.500e+01, 3.000e+00, 2.300e+01, 7.200e+01, 1.260e+02,
       3.400e+01, 4.200e+01, 1.420e+02, 1.580e+02, 1.100e+01, 2.600e+01,
       1.800e+01, 1.310e+02, 1.520e+02, 6.500e+01, 1.410e+02, 1.640e+02,
       9.200e+01, 3.200e+01, 7.600e+01, 8.600e+01, 2.900e+01, 6.800e+01,
       1.840e+02, 6.000e+01, 2.040e+02, 4.770e+02, 1.210e+02, 1.690e+02,
       3.900e+01, 2.280e+02, 4.420e+02, 1.140e+02, 1.560e+02, 4.300e+01,
       9.000e+01, 1.110e+02, 1.950e+02, 2.750e+02, 3.300e+01, 8.900e+01,
       2.240e+02, 2.000e+01, 1.340e+02, 1.650e+02, 

## > Comment on variable `meteo_DRR`

Is not in the dictionary file.  
We will just skip it for now.

## > Comment on variables equal to NaN

NaNs are set such as each row has at least one NaN.  
For now, we will replace them by the mean value.

In [22]:
tiny_train_data_Xy['meteo_radiation_IR'].unique()

array([nan])

In [23]:
train_data['meteo_radiation_IR'].unique()

array([  nan, 2585., 3055., 2996., 3114., 2898., 3076., 3083., 3278.,
       3102., 3044., 3086., 3043., 3094., 3097., 2524., 2336., 2657.,
       2884., 2627., 2667., 2922., 2587., 2561., 2782., 2528., 2761.,
       2616., 2418., 2852., 3085., 3056., 2831., 3031., 3003., 2674.,
       2650., 3069., 3117., 3209., 3067., 2721., 2693., 2703.])

In [24]:
# Drop 'meteo_radiation_IR' because no value in the first 100_000 rows
tiny_train_data_Xy = tiny_train_data_Xy.drop(columns=['meteo_radiation_IR'])

In [25]:
tiny_train_data_X = tiny_train_data_Xy.select_dtypes(include=['int64', 'float64'])
tiny_train_data_X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 105170
Data columns (total 94 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   piezo_station_investigation_depth  93886 non-null   float64
 1   piezo_station_altitude             100000 non-null  float64
 2   piezo_station_longitude            100000 non-null  float64
 3   piezo_station_latitude             100000 non-null  float64
 4   piezo_continuity_code              100000 non-null  float64
 5   piezo_producer_code                94280 non-null   float64
 6   meteo_id                           100000 non-null  int64  
 7   meteo_latitude                     100000 non-null  float64
 8   meteo_longitude                    100000 non-null  float64
 9   meteo_altitude                     100000 non-null  int64  
 10  meteo_rain_height                  99157 non-null   float64
 11  meteo_DRR                          11420 non

In [26]:
tiny_train_data_withoutNA = tiny_train_data_X.fillna(tiny_train_data_X.mean()).join(tiny_train_data['piezo_groundwater_level_category'])
test_data_Xy = test_data.select_dtypes(include=['int64', 'float64']).drop(columns=['meteo_radiation_IR'])
test_data_withoutNA = test_data_Xy.fillna(test_data_Xy.mean())

In [27]:
import numpy as np

X_tiny = tiny_train_data_withoutNA.select_dtypes(include=['int64', 'float64']).to_numpy()
y_tiny = tiny_train_data_withoutNA['piezo_groundwater_level_category'].to_numpy()
X_test = test_data_withoutNA.select_dtypes(include=['int64', 'float64']).to_numpy()

print(X_tiny.shape)
print(y_tiny.shape)
print(X_test.shape)

(100000, 94)
(100000,)
(611208, 94)


In [28]:
from sklearn.model_selection import train_test_split

X_tiny_train, X_tiny_test, y_tiny_train, y_tiny_test = train_test_split(X_tiny, y_tiny, test_size=0.2, random_state=42)
print(X_tiny_train.shape)
print(y_tiny_train.shape)
print(X_tiny_test.shape)
print(y_tiny_test.shape)

(80000, 94)
(80000,)
(20000, 94)
(20000,)


In [29]:
print(y_tiny_train[:5])
print(y_tiny_test[:5])

['High' 'High' 'Very High' 'Very High' 'Very High']
['Low' 'Average' 'Very Low' 'High' 'Very High']


## Model training and prediction

In [30]:
from sklearn.linear_model import LogisticRegression

logistic_regression = LogisticRegression().fit(X_tiny_train, y_tiny_train)

c:\Users\User\anaconda3\envs\map\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [31]:
pred = logistic_regression.predict(X_tiny_test)

print(pred[:100])

['Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Average' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Average' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Average' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Average' 'Very High'
 'Very High' 'Average' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Average'
 'Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'V

In [38]:
from sklearn.metrics import f1_score, confusion_matrix

print(f"Accuracy: {logistic_regression.score(X_tiny_test, y_tiny_test)}")
print(f"F1 score: {f1_score(y_tiny_test, pred, average=None)}")
print(confusion_matrix(y_tiny_test, pred, labels=tiny_train_data_withoutNA['piezo_groundwater_level_category'].unique()))
print(tiny_train_data_withoutNA['piezo_groundwater_level_category'].unique())

Accuracy: 0.2432
F1 score: [0.13696397 0.00400364 0.         0.3818918  0.        ]
[[  11 4979    0    0  425]
 [  27 4433    0    0  339]
 [   0 1820    0    0  114]
 [  22 2995    0    0  205]
 [  20 4190    0    0  420]]
['High' 'Very High' 'Very Low' 'Low' 'Average']


In [39]:
confusion_matrix(y_tiny_test, pred, labels=tiny_train_data_withoutNA['piezo_groundwater_level_category'].unique())

array([[  11, 4979,    0,    0,  425],
       [  27, 4433,    0,    0,  339],
       [   0, 1820,    0,    0,  114],
       [  22, 2995,    0,    0,  205],
       [  20, 4190,    0,    0,  420]], dtype=int64)

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_tiny_test, pred, labels=tiny_train_data_withoutNA['piezo_groundwater_level_category'].unique()))

c:\Users\User\anaconda3\envs\map\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

        High       0.14      0.00      0.00      5415
   Very High       0.24      0.92      0.38      4799
    Very Low       0.00      0.00      0.00      1934
         Low       0.00      0.00      0.00      3222
     Average       0.28      0.09      0.14      4630

    accuracy                           0.24     20000
   macro avg       0.13      0.20      0.10     20000
weighted avg       0.16      0.24      0.12     20000



c:\Users\User\anaconda3\envs\map\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\anaconda3\envs\map\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [35]:
print(y_tiny_test[:5])
print(pred[:10])

['Low' 'Average' 'Very Low' 'High' 'Very High']
['Very High' 'Very High' 'Very High' 'Very High' 'Very High' 'Very High'
 'Very High' 'Very High' 'Average' 'Very High']


## Logistic Regression coefficients

In [36]:
print(logistic_regression.coef_)

[[-1.85932532e-18  3.55446665e-18  6.93486460e-20  6.56023144e-19
   2.65596490e-20  6.58091045e-15  5.66021502e-13  6.85431217e-20
   6.55891569e-19  4.41342571e-18  1.94413724e-20  1.51111565e-18
   1.87923998e-20  1.33388488e-17  1.05227061e-19  1.67198108e-17
   6.03114961e-20  6.22297094e-20  1.19916538e-20  2.60429879e-20
   2.72880196e-18  8.68925823e-20  6.25383811e-20  1.36683584e-17
   1.36211039e-17  4.59323464e-20  1.46780990e-19  2.49301887e-18
   1.74476328e-17  8.91640246e-20  2.44992294e-18  1.70029602e-17
   2.48204791e-20  9.86747697e-20  2.51528405e-18  1.87763664e-17
   1.37972570e-19  1.74014790e-17  9.20883064e-19  1.69128045e-17
   1.27136184e-18  1.21978601e-17  9.55101536e-20  1.36750514e-17
   1.03889948e-19  1.22249567e-18  1.13212311e-18  2.64258019e-18
   6.49542379e-18  8.38829985e-18  4.86111933e-19  1.56650875e-20
   9.35501555e-20  1.34487346e-18  2.38802549e-22  3.72169841e-21
   2.87742207e-22  2.65222246e-22  3.04297528e-22  8.04561232e-22
   1.27829

In [37]:
print(logistic_regression.coef_.shape)

(5, 94)
